import Foundation
import Testing
@testable import PanelBarCore

@Suite("Localization")
struct LocalizationTests {
    @Test func systemLanguageResolution() {
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["zh-Hans-CN", "en-US"]) == .zhHans)
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["ja-JP", "en"]) == .ja)
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["de-DE", "en"]) == .de)
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["es-ES", "en"]) == .es)
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["fr-FR", "en"]) == .fr)
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["tr-TR", "en"]) == .tr)
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["en-GB"]) == .en)
        #expect(AppLanguage.resolveSystemLanguage(preferredLanguages: ["it-IT", "ru-RU"]) == .en)
    }

    @Test func languageStringsNonEmpty() {
        for lang in AppLanguage.supportedLanguages {
            let s = lang.strings
            #expect(!s.settings.isEmpty)
            #expect(!s.languageTitle.isEmpty)
            #expect(!s.systemDefault.isEmpty)
            #expect(!s.back.isEmpty)
            #expect(!s.cancel.isEmpty)
            #expect(!s.done.isEmpty)
            #expect(!s.quit.isEmpty)
            #expect(!s.quitApp.isEmpty)
            #expect(!s.quitTooltip.isEmpty)
            #expect(!s.settingsTooltip.isEmpty)
            #expect(!s.refreshTooltip.isEmpty)
            #expect(!s.refresh.isEmpty)
            #expect(!s.changesSaveInstantly.isEmpty)
            #expect(!s.menuBarSection.isEmpty)
            #expect(!s.showNextToIcon.isEmpty)
            #expect(!s.statIconOnly.isEmpty)
            #expect(!s.statDiskAccounts.isEmpty)
            #expect(!s.statSSLDaysServices.isEmpty)
            #expect(!s.iconAndDotOnlyWhenOffline.isEmpty)
            #expect(!s.refreshSection.isEmpty)
            #expect(!s.whilePopoverOpen.isEmpty)
            #expect(!s.refreshGentleNote.isEmpty)
            #expect(!s.inTheBackground.isEmpty)
            #expect(!s.minutes(count: 5).isEmpty)
            #expect(!s.off.isEmpty)
            #expect(!s.generalSection.isEmpty)
            #expect(!s.launchAtLogin.isEmpty)
            #expect(!s.approveInLoginItems.isEmpty)
            #expect(!s.appearance.isEmpty)
            #expect(!s.appearanceSystem.isEmpty)
            #expect(!s.appearanceLight.isEmpty)
            #expect(!s.appearanceDark.isEmpty)
            #expect(!s.securitySection.isEmpty)
            #expect(!s.protectWithTouchID.isEmpty)
            #expect(!s.touchIDDetailAvailable.isEmpty)
            #expect(!s.touchIDDetailUnavailable.isEmpty)
            #expect(!s.touchIDPromptEnable.isEmpty)
            #expect(!s.touchIDPromptDisable.isEmpty)
            #expect(!s.touchIDPromptDelete.isEmpty)
            #expect(!s.touchIDPromptEdit(name: "Test").isEmpty)
            #expect(!s.enabled.isEmpty)
            #expect(!s.disabled.isEmpty)
            #expect(!s.unavailable.isEmpty)
            #expect(!s.serversSection.isEmpty)
            #expect(!s.active.isEmpty)
            #expect(!s.editServer.isEmpty)
            #expect(!s.deleteServer.isEmpty)
            #expect(!s.addAnotherServer.isEmpty)
            #expect(!s.privacySection.isEmpty)
            #expect(!s.privacyNote.isEmpty)
            #expect(!s.aboutSection.isEmpty)
            #expect(!s.unofficialDisclaimer(version: "1.0.0").isEmpty)
            #expect(!s.checkForUpdates.isEmpty)
            #expect(!s.checkingForUpdates.isEmpty)
            #expect(!s.upToDate(version: "1.0.0").isEmpty)
            #expect(!s.updateAvailable(version: "1.0.0").isEmpty)
            #expect(!s.viewRelease.isEmpty)
            #expect(!s.manualCheckOnlyNote.isEmpty)
            #expect(!s.sourceCodeOnGitHub.isEmpty)
            #expect(!s.activeServer.isEmpty)
            #expect(!s.addServer.isEmpty)
            #expect(!s.addServerEllipsis.isEmpty)
            #expect(!s.addAServer.isEmpty)
            #expect(!s.noServerConnected.isEmpty)
            #expect(!s.addServerDescription.isEmpty)
            #expect(!s.tokenRejected.isEmpty)
            #expect(!s.tokenRejectedBody(host: "example.com").isEmpty)
            #expect(!s.unreachable.isEmpty)
            #expect(!s.couldNotConnect(host: "example.com").isEmpty)
            #expect(!s.apiToken.isEmpty)
            #expect(!s.pasteNewToken.isEmpty)
            #expect(!s.saveToken.isEmpty)
            #expect(!s.retry.isEmpty)
            #expect(!s.statusOnline.isEmpty)
            #expect(!s.statusOffline.isEmpty)
            #expect(!s.statusNeedsToken.isEmpty)
            #expect(!s.statusLocked.isEmpty)
            #expect(!s.checking.isEmpty)
            #expect(!s.lastChecked(time: "now").isEmpty)
            #expect(!s.justNow.isEmpty)
            #expect(!s.secondsAgo(count: 10).isEmpty)
            #expect(!s.minutesAgo(count: 5).isEmpty)
            #expect(!s.domainsHosted.isEmpty)
            #expect(!s.accountsHosted.isEmpty)
            #expect(!s.openCPanel.isEmpty)
            #expect(!s.openWHM.isEmpty)
            #expect(!s.openCPanelInBrowser.isEmpty)
            #expect(!s.openWHMInBrowser.isEmpty)
            #expect(!s.plainHTTPAnywayWarning.isEmpty)
            #expect(!s.tabOverview.isEmpty)
            #expect(!s.tabDomains.isEmpty)
            #expect(!s.tabAccounts.isEmpty)
            #expect(!s.tabServices.isEmpty)
            #expect(!s.resources.isEmpty)
            #expect(!s.accountAndServer.isEmpty)
            #expect(!s.cpanelUser.isEmpty)
            #expect(!s.serverHost.isEmpty)
            #expect(!s.primaryDomain.isEmpty)
            #expect(!s.portAndProtocol.isEmpty)
            #expect(!s.quickActions.isEmpty)
            #expect(!s.copyHost.isEmpty)
            #expect(!s.serverAddress.isEmpty)
            #expect(!s.diskLimit(limit: "100 MB").isEmpty)
            #expect(!s.diskUsedUnlimited.isEmpty)
            #expect(!s.percentUsed(percent: 50).isEmpty)
            #expect(!s.noQuotaLimit.isEmpty)
            #expect(!s.nextSSLExpiry.isEmpty)
            #expect(!s.noCertificates.isEmpty)
            #expect(!s.domainsHostedCount(count: 1).isEmpty)
            #expect(!s.domainsHostedCount(count: 3).isEmpty)
            #expect(!s.subAddon(count: 2).isEmpty)
            #expect(!s.noneHosted.isEmpty)
            #expect(!s.sslProtection.isEmpty)
            #expect(!s.noDomains.isEmpty)
            #expect(!s.allDomainsCovered.isEmpty)
            #expect(!s.unprotected(count: 2).isEmpty)
            #expect(!s.filterDomains.isEmpty)
            #expect(!s.tableHeaderDomain.isEmpty)
            #expect(!s.tableHeaderType.isEmpty)
            #expect(!s.tableHeaderSSL.isEmpty)
            #expect(!s.noMatches.isEmpty)
            #expect(!s.copyDomain.isEmpty)
            #expect(!s.systemSection.isEmpty)
            #expect(!s.hostname.isEmpty)
            #expect(!s.whmVersion.isEmpty)
            #expect(!s.adminUser.isEmpty)
            #expect(!s.suspendedCount(count: 1).isEmpty)
            #expect(!s.allActive.isEmpty)
            #expect(!s.none.isEmpty)
            #expect(!s.loadAverage.isEmpty)
            #expect(!s.loadAverage1m.isEmpty)
            #expect(!s.diskUsed.isEmpty)
            #expect(!s.summedAcrossAccounts(count: 4).isEmpty)
            #expect(!s.summingAccounts.isEmpty)
            #expect(!s.servicesOnline.isEmpty)
            #expect(!s.allMonitoredRunning.isEmpty)
            #expect(!s.servicesDown(count: 1).isEmpty)
            #expect(!s.servicesDownCardTitle.isEmpty)
            #expect(!s.inspect.isEmpty)
            #expect(!s.accountSuspendedTitle(count: 1).isEmpty)
            #expect(!s.accountSuspendedTitle(count: 2).isEmpty)
            #expect(!s.view.isEmpty)
            #expect(!s.tableHeaderAccount.isEmpty)
            #expect(!s.tableHeaderDisk.isEmpty)
            #expect(!s.tableHeaderService.isEmpty)
            #expect(!s.tableHeaderStatus.isEmpty)
            #expect(!s.suspended.isEmpty)
            #expect(!s.serviceUp.isEmpty)
            #expect(!s.serviceDown.isEmpty)
            #expect(!s.serviceNotMonitored.isEmpty)
            #expect(!s.serviceNotInstalled.isEmpty)
            #expect(!s.viewAccountDetails.isEmpty)
            #expect(!s.copyUsername.isEmpty)
            #expect(!s.accountInformation.isEmpty)
            #expect(!s.username.isEmpty)
            #expect(!s.contactEmail.isEmpty)
            #expect(!s.ipAddress.isEmpty)
            #expect(!s.hostingPackage.isEmpty)
            #expect(!s.owner.isEmpty)
            #expect(!s.createdDate.isEmpty)
            #expect(!s.cpanelTheme.isEmpty)
            #expect(!s.quotasAndLimits.isEmpty)
            #expect(!s.diskUsage.isEmpty)
            #expect(!s.maxAddonDomains.isEmpty)
            #expect(!s.maxSubdomains.isEmpty)
            #expect(!s.maxEmailAccounts.isEmpty)
            #expect(!s.maxSQLDatabases.isEmpty)
            #expect(!s.inodes.isEmpty)
            #expect(!s.usedOf(used: "10 MB", limit: "100 MB").isEmpty)
            #expect(!s.quotaPercent(percent: 10).isEmpty)
            #expect(!s.copyUser.isEmpty)
            #expect(!s.serverType.isEmpty)
            #expect(!s.cpanelAccount.isEmpty)
            #expect(!s.whmServer.isEmpty)
            #expect(!s.singleSiteAgency.isEmpty)
            #expect(!s.fullServerManager.isEmpty)
            #expect(!s.connectionDetails.isEmpty)
            #expect(!s.displayName.isEmpty)
            #expect(!s.hostURL.isEmpty)
            #expect(!s.authentication.isEmpty)
            #expect(!s.tokenHelpCPanel.isEmpty)
            #expect(!s.tokenHelpWHM.isEmpty)
            #expect(!s.plainHTTPWarning.isEmpty)
            #expect(!s.plainHTTPDescription.isEmpty)
            #expect(!s.allowUnencryptedHTTP.isEmpty)
            #expect(!s.testConnection.isEmpty)
            #expect(!s.testing.isEmpty)
            #expect(!s.saveAndConnect.isEmpty)
            #expect(!s.saveChanges.isEmpty)
            #expect(!s.serverConnection.isEmpty)
            #expect(!s.serverName.isEmpty)
            #expect(!s.verifyConnection.isEmpty)
            #expect(!s.connecting.isEmpty)
            #expect(!s.verifyingCredentials.isEmpty)
            #expect(!s.dangerZone.isEmpty)
            #expect(!s.deleteThisConnection.isEmpty)
            #expect(!s.deleteConnectionDescription.isEmpty)
            #expect(!s.delete.isEmpty)
            #expect(!s.areYouSureCannotBeUndone.isEmpty)
            #expect(!s.confirmDelete.isEmpty)
            #expect(!s.onboardingWelcomeTag.isEmpty)
            #expect(!s.welcomeToPanelBar.isEmpty)
            #expect(!s.onboardingSubtitle.isEmpty)
            #expect(!s.onboardingBullet1.isEmpty)
            #expect(!s.onboardingBullet2.isEmpty)
            #expect(!s.getStarted.isEmpty)
            #expect(!s.connectAccountOrServer.isEmpty)
            #expect(!s.connectStepSubtitle.isEmpty)
            #expect(!s.saveAnyway.isEmpty)
            #expect(!s.connectAndContinue.isEmpty)
            #expect(!s.youreConnected.isEmpty)
            #expect(!s.saved.isEmpty)
            #expect(!s.openPanelBar.isEmpty)
            #expect(!s.onboardingTip1.isEmpty)
            #expect(!s.onboardingTip2.isEmpty)
            #expect(!s.onboardingTip3.isEmpty)
        }
    }

    @Test func appSettingsLanguageRoundTrip() {
        let name = "panelbar.tests.lang.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: name)!
        defaults.removePersistentDomain(forName: name)

        var settings = AppSettings.load(from: defaults)
        #expect(settings.language == .system)

        settings.language = .tr
        settings.save(to: defaults)

        let reloaded = AppSettings.load(from: defaults)
        #expect(reloaded.language == .tr)
    }
}
